language: java
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_ab15aaaef74e_key -iv $encrypted_ab15aaaef74e_iv -in application.properties.enc -out
bangladesh-green/src/main/resources/application.properties -d